### ISSUE TITLE
Build fail: missing dependency: com.google.android.tools:dx:23.0.0

### ISSUE THREAD

**Issue by Lanchon** [pxb1988/dex2jar#140]
hi,

`com.google.android.tools:dx:23.0.0` vanished and the build no longer works, unless you have the artifact in your local cache.

where was this previously located? was it here?
http://repository-dex2jar.forge.cloudbees.com/release/com/google/android/tools/dx/23.0.0/

note that this repo is no longer up:
http://repository-dex2jar.forge.cloudbees.com/
what was there before?

btw, google is known for removing their old open source software from everywhere, the way they are doing with older versions of Android Studio, and i personally think it's risky to use their repos.

**Comment by yevgenyk** [comment]
Remove that line in build.gradle 
It does not seem to be used.

**Comment by Lanchon** [comment]
thanks. hmmm... this file is copied on all builds to the lib directory.
anyway, here are the files... [dx-23.0.0.zip](https://github.com/pxb1988/dex2jar/files/1326201/dx-23.0.0.zip)

**Comment by BackTrackCRoot** [comment]
I have this problem too...  where is com.google.android.tools:dx:23.0.0 ?

**Comment by yevgenyk** [comment]
In the root of the project:
./gradlew install
You will get an error about a missing com.google.android.tools:dx:23.0.0
Go to dex-tools/build.gradle file and remove this line:
  compile "com.google.android.tools:dx:23.0.0"
Try
./gradlew install
again. 

The compilation will succeed and the jar will end up in:
/dex2jar/dex-tools/build/libs/dex-tools-2.1-SNAPSHOT.jar

You can either use this jar directly or replace your older version of dex-tools.jar with this one.

**Comment by BackTrackCRoot** [comment]
@yevgenyk Thanks~ it seems ok. but how to replace ?

**Comment by friederbluemle** [comment]
Interesting. Someone must have **removed** the `23.0.0` version of `com.google.android.tools:dx` from the referenced repositories. That's concerning. Looking at [mvnrepository](https://mvnrepository.com/artifact/com.google.android.tools/dx), the *only* version available there is `1.7`.

The project does *compile* (`./gradlew assemble`), if you just replace `23.0.0` with `1.7`.

However, a test in `TestUtils` (`dex-translator`) will fail. The reason is that the signature of `CfTranslator.translate` has changed.
Version `23.0.0` seems to suggest that the dependency is related to the Android build-tools shipped in August 2015. The `dx` included in `23.0.0` was `1.11` though, whereas the only version available to us (`1.7`) likely originated from a very old version of the build tools - probably `18.0.0` (released in 2013). I didn't do any further investigation if a quick and easy fix for the test is possible.

**Comment by fatalbit** [comment]
As a workaround, using Lanchon's link I was able to add a local url to the build root's build.gradle. Doing so makes gradle look for dx in the local file system. I added url "../" as a repo and placed the respective files in dex2jar/com/google/android/tools/dx/23.0.0/* and it resolves correctly.

**Comment by zoe0316** [comment]
download Lanchon's link zip file copy the dx-23.0.0.jar to  dex-tools/lib 
```
mkdir dex-tools/lib && mv [PATH of dx-23.0.0.jar] dex-tools/lib

vim dex-tools/build.gradle
# compile files("lib/dx-23.0.0.jar")
gradle clean distZip
```

**Comment by friederbluemle** [comment]
It is no longer necessary to manually copy `dx-23.0.0.jar` - A new file `dx-27.0.3.jar` was added to the repo in ffd6e395b82d954a9cc31a793edb0266076e536c on Apr 2nd 2018, fixing the problem.
This issue can be closed.
